package com.farnest.common.model;

//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2016.04.28 at 11:08:53 AM BST 
//

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hotel", propOrder = {
 "hotelid",
 "name",
 "address1",
 "address2",
 "postalCode",
 "thumbNail",
 "rate"
})

@Entity
@Table(name="hotels")
@XmlRootElement(name = "hotel")
public class HotelSummary implements Serializable {
	public int getHotelid() {
		return hotelid;
	}

	public void setHotelid(int hotelid) {
		this.hotelid = hotelid;
	}

	@Id
 @GeneratedValue
 protected int hotelid;
 @XmlElement(required = true)
 protected String name;
 @XmlElement(required = true)
 protected String address1;
 @XmlElement(required = true)
 protected String address2;
 @XmlElement(required = true)
 protected String postalCode;
 @XmlElement(required = true)
 protected String thumbNail;
 @XmlElement(required = true)
 protected String lowRate;
 
 @XmlElement(required = true)
 protected String locationDescription;

 @XmlElement(required = true)
 protected String countryCode;
 
 @XmlElement(required = true)
 protected String rateCurrencyCode;
 
 
 
 public String getRateCurrencyCode() {
		return rateCurrencyCode;
	}

	public void setRateCurrencyCode(String rateCurrencyCode) {
		this.rateCurrencyCode = rateCurrencyCode;
	}

	@XmlElement(required = true)
 protected String shortDescription;
 
 

 public String getShortDescription() {
		return shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@XmlElement(required = true)
 protected String city;
 
 
 public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getLocationDescription() {
		return locationDescription;
	}

	public void setLocationDescription(String locationDescription) {
		this.locationDescription = locationDescription;
	}


 /**
  * Gets the value of the name property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getName() {
     return name;
 }

 /**
  * Sets the value of the name property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setName(String value) {
     this.name = value;
 }

 /**
  * Gets the value of the address1 property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getAddress1() {
     return address1;
 }

 /**
  * Sets the value of the address1 property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setAddress1(String value) {
     this.address1 = value;
 }

 /**
  * Gets the value of the address2 property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getAddress2() {
     return address2;
 }

 /**
  * Sets the value of the address2 property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setAddress2(String value) {
     this.address2 = value;
 }

 /**
  * Gets the value of the postalCode property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getPostalCode() {
     return postalCode;
 }

 /**
  * Sets the value of the postalCode property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setPostalCode(String value) {
     this.postalCode = value;
 }

 /**
  * Gets the value of the thumbNail property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getThumbNail() {
     return thumbNail;
 }

 /**
  * Sets the value of the thumbNail property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setThumbNail(String value) {
     this.thumbNail = value;
 }

 /**
  * Gets the value of the rate property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getLowRate() {
     return lowRate;
 }

 /**
  * Sets the value of the rate property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setLowRate(String value) {
     this.lowRate = value;
 }

 @Override
 public String toString() {
     return "Hotel:"
       +hotelid
      +"|"+name
      +"|"+address1 
      +"|"+address2 
      +"|"+postalCode 
      +"|"+thumbNail 
      +"|"+lowRate;
     
 }    
 
 public HotelSummary(){}
}
